// This file is generated by Astro DB
declare module 'astro:db' {
	export const User: import("@astrojs/db/runtime").Table<
		"User",
		{"id":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"id","collection":"User","primaryKey":true}},"email":{"type":"text","schema":{"unique":true,"deprecated":false,"name":"email","collection":"User","primaryKey":false,"optional":false}},"user_type":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"user_type","collection":"User","primaryKey":false,"optional":false}},"hashed_password":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"hashed_password","collection":"User","primaryKey":false,"optional":false}}}
	>;
	export const Session: import("@astrojs/db/runtime").Table<
		"Session",
		{"id":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Session","primaryKey":true}},"expiresAt":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"expiresAt","collection":"Session"}},"userId":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"userId","collection":"Session","primaryKey":false,"optional":false,"references":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"id","collection":"User","primaryKey":true}}}}}
	>;
	export const Family: import("@astrojs/db/runtime").Table<
		"Family",
		{"id":{"type":"text","schema":{"unique":true,"deprecated":false,"name":"id","collection":"Family","primaryKey":true}},"prefix":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"prefix","collection":"Family","default":"Familia","primaryKey":false,"optional":false}},"name":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"name","collection":"Family","primaryKey":false,"optional":false}},"numTickets":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"numTickets","collection":"Family","primaryKey":false,"optional":false}},"invitationAccepted":{"type":"boolean","schema":{"optional":false,"unique":false,"deprecated":false,"name":"invitationAccepted","collection":"Family"}},"acceptedDate":{"type":"date","schema":{"optional":true,"unique":false,"deprecated":false,"name":"acceptedDate","collection":"Family"}},"createdBy":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"createdBy","collection":"Family","default":"system","primaryKey":false,"optional":false}},"createdAt":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"createdAt","collection":"Family","default":"2025-07-09T16:43:41.576Z"}}}
	>;
}
